[package]
name = "mab_font"
version = "0.1.0"
authors = ["viperscape <chrisfgill@gmail.com>"]

[dependencies]
font-atlas = "0.1.0"
font-atlas-freetype = "0.1.0"
font-atlas-image = "0.1.0"
freetype-rs = "*"
image = "*"